#!/usr/bin/env python3
"""Regenerate src/fonts.mjs (Sarabun, base64) from mot-dang/assets/fonts."""
import base64, os
SRC = os.path.expanduser('~/Developer/claude code projects/mot-dang/assets/fonts/')
out = ['// fonts.mjs — Sarabun (SIL Open Font License), the Mot Dang face, as base64 for',
       '// the share-card renderer, which runs with no network. Generated by',
       '// scripts/make-fonts.py from mot-dang/assets/fonts; do not edit by hand.']
for n in ['sarabun-600-thai', 'sarabun-600-latin', 'sarabun-400-thai', 'sarabun-400-latin']:
    b = base64.b64encode(open(SRC + n + '.woff2', 'rb').read()).decode()
    out.append(f"export const {n.replace('-', '_').upper()} = '{b}'")
open(os.path.join(os.path.dirname(__file__), '..', 'src', 'fonts.mjs'), 'w').write('\n'.join(out) + '\n')
